config/routes.rb
Rails.application.routes.draw do
  root 'artists#index'

  resources :artists, only: [:new, :create, :show]

  resources :guitars, only: [:new, :create, :show]
  resources :amps, only: [:new, :create, :show]
  resources :effects, only: [:new, :create, :show]

end

app/models/amp.rb
class Amp < Gear
end

app/models/artist.rb
class Artist < ActiveRecord::Base
  has_many :gear

  def name
    first_name + ' ' + last_name
  end

end

app/models/effect.rb
class Effect < Gear
end

app/models/gear.rb
class Gear < ActiveRecord::Base
  belongs_to :artist
end

app/models/guitar.rb
class Guitar < Gear
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController

  def index
  end

  def show
    @artist = Artist.find(params[:id])
  end

  def new
    @artist = Artist.new
  end

  def create
    artist = Artist.create(artist_params)
    redirect_to artist
  end

  private

  def artist_params
    params.require(:artist).permit(:first_name, :last_name, :bio, :image, :band)
  end

end

app/controllers/gear_controller.rb
class GearController < ApplicationController

  def show
  end

  def new
  end

  def create
  end

end

app/controllers/guitars_controller.rb
class GuitarsController < ApplicationController

  def new
    @guitar = Guitar.new
  end

  def create
    Guitar.create(guitar_params)
    redirect_to root_path
  end

  private

  def guitar_params
    params.require(:guitar).permit(:name, :description)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/artists/index.html.erb
<h1>Hello, welcome to the artist index page!</h1>

<%= link_to 'Add New Artist', new_artist_path %>

app/views/artists/new.html.erb
<h2>Add a New Artist</h2>

<%= form_for @artist do |form| %>
  <%= form.label 'First Name:' %>
  <%= form.text_field :first_name %>
  <%= form.label 'Last Name:' %>
  <%= form.text_field :last_name %>
  <%= form.label 'Artist Image:' %>
  <%= form.text_field :image %>
  <%= form.label 'Associated Acts:' %>
  <%= form.text_field :band %>
  <%= form.submit %>
<% end %>

app/views/artists/show.html.erb
<h1><%= @artist.name %></h1>

<%= link_to 'Add New Guitar', new_guitar_path %>

app/views/guitars/new.html.erb
<h1>Add a New Guitar</h2>

<%= form_for @guitar do |form| %>
  <%= form.label 'Name: ' %>
  <%= form.text_field :name %>
  <%= form.label 'Description' %>
  <%= form.text_area :description %>
  <%= form.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GearHub</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>